//COS'è UN ALGORITMO
UN ALGORITMO è UN INSIEME DI ELEMENTI CHE MESSI INSIEME RIESCONO A REALIZZARE UN RISULTATO SPECIFICO 
//COS'è UNA VARIABILE
LA VARIABILE è L'ELEMENTO CHE CI FARà FARE L'ALGORITMO
//UNDEFINE E NULL SONO LA STESSA COSA?
NO, UNDEFINED è UN VALORE CHE NON è ANCORA DEFINITO.
NULL INVECE è PROPRIO UNA VARIABILE CHE NON HA VALORE.